name: duct
version: 0.0.1
description: socket.io in Dart
author: Petr Hosek
homepage: http://github.com/petrh/duct
dependencies:
  dartredisclient:
    git: git://github.com/Dartist/RedisClient.git
  benchmark_harness: ">=1.0.0 <2.0.0"
  logging: ">=0.2.10"
  unittest: ">=0.2.8"